### ISSUE TITLE
HTTPS のサイトに embed コードを貼り付けてもスライドが埋め込めない

### ISSUE THREAD

**Issue by tricknotes** [rabbit-shocker/slide.rabbit-shocker.org#2]
現在 slide.rabbit-shocker.org は https に非対応のため、https で公開されているサイトに embed コードを貼り付けるとブラウザの設定によってはスライドの読み込みがブロックされてしまいます。
参考: https://support.mozilla.org/ja/kb/mixed-content-blocking-firefox 

スライドがブロックされるのは、例えばこちらのページです。
https://oss-gate.github.io/report/workshop/2016/06/11/workshop-report.html

Chrome (51.0.2704.103 (64-bit)) でこのページを表示すると、次のメッセージが開発者コンソールに表示されます。
> Mixed Content: The page at 'https://oss-gate.github.io/report/workshop/2016/06/11/workshop-report.html' was loaded over HTTPS, but requested an insecure resource 'http://slide.rabbit-shocker.org/authors/kou/oss-gate-workshop-tutorial-conclusion/viewer.html'. This request has been blocked; the content must be served over HTTPS.

もし slide.rabbit-shocker.org が https に対応していれば、https のページでもスライドがブロックされることなく読み込めて幸せになれると思いました。

**Comment by kou** [comment]
対応しました。
