### ISSUE TITLE
https://slide.rabbit-shocker.org/ で検索するとエラーが発生する

### ISSUE THREAD

**Issue by urimaro** [rabbit-shocker/slide.rabbit-shocker.org#3]
## 事象

https://slide.rabbit-shocker.org/ で検索するとエラーが発生して、検索結果が表示されません。

![image](https://user-images.githubusercontent.com/752746/64916047-501ffb80-d7b0-11e9-97fe-8b8dfba76d3c.png)

## 再現手順

1. https://slide.rabbit-shocker.org/ にアクセスする
2. 検索条件として「a」を入力し、Enterを押下する

**Comment by kou** [comment]
報告ありがとうございます。
Rubyのバージョンを上げたあとに`bundle install`しなおしていないせいでした。
直しました。

**Comment by daipom** [comment]
現在同じ現象が発生しています。

2023-04-14T16:53

URI:

```
https://slide.rabbit-shocker.org/search/?query=a#
```

![Screenshot from 2023-04-14 16-53-32](https://user-images.githubusercontent.com/12229857/231980847-c34bf656-d836-4235-9c9c-04b52572e1a4.png)

環境

* Ubuntu 20.04
* Firefox 112.0

**Comment by kou** [comment]
さーせん。。。
default gemのバージョンミスマッチになっていました。
（違う原因。）

根本的に直すにはどこをいい感じにするといいのかしら。。。Passengerか、Bundlerか、なのかしら。。。

**Comment by daipom** [comment]
ありがとうございます！
検索できるようになりました！

(今度はPRを作れるようになっていたいな、、)

**Comment by daipom** [comment]
> 根本的に直すにはどこをいい感じにするといいのかしら。。。Passengerか、Bundlerか、なのかしら。。。

なるほど、よく分かっていないですが、
このリポジトリーはまだ修正していなくて、サーバー側？を直接直した状態なんですね

**Comment by kou** [comment]
デプロイの仕方の問題なのでこのアプリケーションで云々できる話じゃないんですよねぇ。
